### ISSUE TITLE
Outdated for 1.12 BungeeCord? - Unable to Process / Drop Votes (java.io.IOException)

### ISSUE THREAD

**Issue by NotStarRift** [parallelblock/NuVotifier#27] opened 2017-08-01 20:00 UTC
Howdy, I have properly configured the latest version of nuVotifier for my 1.12 Bungeecord network. However, for a lot of sites it seems to drop votes. I have check my firewalls, ports, and tested using the tool and other voting sites. Some work, but not all the time. Here's a paste of the debug output from my console:
https://pastebin.com/yb7gYSqa

**Comment by BashPvP** [comment] 2017-08-01 20:01
I forgot to mention the the site does come back with it as a verified vote, but the server itself cannot process it.

**Comment by Ichbinjoe** [comment] 2017-11-01 16:04
This exception is solely caused by the other host. Is this a v1 sender (a serverlist or something?)

**Comment by mkcoldwolf** [comment] 2018-01-07 11:06
Same Problem Here , Still not fixed , i have checked all things already, and those Plugin were worked on Old version of bungee

**Comment by Ichbinjoe** [comment] 2018-01-07 14:54
Nothing changed in NuVotifier between 1.11 and 1.12 for the sake of comparability between the servers. However, this should not be necessary, seeing as NuVotifier brings in all of its dependencies (assuming a standard build) with it, and only requires bungee cords plugin and event loops which have no changed in some time from what I know. Seeing as this appears to be a proto issue, I find it hard to believe this isolated section of code is affected by bungee 1.12. That being said: are these disconnects happening on the bungee cord server logs or the actual game spigot/sponge server logs and is instead due to a forwarding issue? Could a net topology be shared with configurations (credentials removed)

**Comment by mkcoldwolf** [comment] 2018-01-07 16:15
Dont get it , im trying to put it as a Bungee Plugin dependencies and only boradcast the message on Bungee, After i try again, that Error seems showing randomly and my Vote Plugin that worked in pass not work , alough it showing the Error , I still can the get vote info "Got a protocol v1 vote record from xxx" , i think the issue will be my Event that in my Plugin, ill look some more info about it, thanks for reply!

**Comment by Ichbinjoe** [comment] 2018-01-16 03:55
@BashPvP Not sure if you are still using NuVotifier, but if you are, is that message immediately preceded by a 'Got a protocol....' message? If so, vote sites may be prematurely closing voting sockets. If thats so, we can silence the exception in this circumstance because it is incorrect.

**Comment by mpoloskey** [comment] 2018-02-25 20:28
Having the same problem,  Unable to process votes.

it's a good idea to silence the exception and still process the vote if the socket is closed prematurely
.
This would make a lot of our voters happy, so really would like to see this fixed in a short timne.

**Comment by Ichbinjoe** [comment] 2018-02-25 21:50
In the case I described above the votes are still processed, but the stack trace is _in addition_ displayed. This issue may not result in a loss of votes. We can’t always recover the vote however, since If we don’t actually get a vote before the connection is closed, then we don’t actually know how to decode the vote...

**Comment by Ichbinjoe** [comment] 2018-02-25 21:50
If the connection is closed before we can decode the vote, there is nothing this plugin can even do.

**Comment by Ichbinjoe** [comment] 2018-03-29 01:50
Unless anyone has any other information for this issue, I'm closing the issue as there is nothing else that we can really do.

I would appriciate more information, and if there is any from anyone in this thread, then feel free to post and I'll reopen the issue.

**Comment by mkcoldwolf** [comment] 2018-03-29 04:35
But I am wondering how its still can show the vote username and votesite at #53 isn't it enough for processing a vote to server?

**Comment by Ichbinjoe** [comment] 2018-03-29 04:41
@mkcoldwolf it sounds the 'problem' is what i describe above:

> @ bashpvp Not sure if you are still using NuVotifier, but if you are, is that message immediately preceded by a 'Got a protocol....' message? If so, vote sites may be prematurely closing voting sockets. If thats so, we can silence the exception in this circumstance because it is incorrect.

So I think the appropriate action to close out this issue is to silence the exception if a vote has already been processed.

Note this is more of a logging issue and not an application issue, as per my later comment:

> In the case I described above the votes are still processed, but the stack trace is in addition displayed. This issue may not result in a loss of votes. We can’t always recover the vote however, since If we don’t actually get a vote before the connection is closed, then we don’t actually know how to decode the vote...

**Comment by mkcoldwolf** [comment] 2018-03-29 04:48
Okay thank you

**Comment by Ichbinjoe** [comment] 2018-03-29 05:06
This fix is now on the CI build of NuVotifier. You can pick up the latest of that build here: https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

I am once again closing this issue. If anyone feels that the above build does not fix these exceptions, and thinks NuVotifier is dropping votes due to IO related exceptions, please post back with an updated log / configuration as well as which service is causing the dropped votes.

**Closed by Ichbinjoe** 2018-03-29 05:06 UTC

**Comment by Gregory1346** [comment] 2018-04-29 21:16
Only Planetminecraft. Tried that version. Topg, PMC, MCSL, Minecraft-mp all work. MinecraftForum doesn't. Always gives the bungee proxy this stacktrace:
22:12:29 [SEVERE] [NuVotifier] Unable to process vote from /52.44.191.1:62624
java.io.IOException: An existing connection was forcibly closed by the remote host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(Unknown Source)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.IOUtil.read(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
    at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
    at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
    at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
    at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
