### ISSUE TITLE
Votes Forwarding Issues

### ISSUE THREAD

**Issue by AmazedMender16** [parallelblock/NuVotifier#96] opened 2018-09-02 19:07 UTC
Hello,

I have set NuVotifier on the bungee to forward votes to 4 gamemodes, tho after some time NuVotifier stops forwarding the votes. After restarting the gamemodes it all starts working again.

Regards,
Glenn R.

**Comment by L4BORG** [comment] 2018-09-06 01:33
I think we have the same issue, but it seems like it's random, sometimes it would work sometimes not. When we tried logging votes on BungeeCord it always worked, but sometimes votes just won't reach spigot instances, sometimes they would only reach some spigot instances behind the same BungeeCord.

**Comment by L4BORG** [comment] 2018-09-06 01:33
Tested with all NuVotifier versions between 2.3.4 and latest.

**Comment by L4BORG** [comment] 2018-09-06 15:39
We're also running only 1 BungeeCord server (latest build) and spigot servers are latest 1.8.8. The issue was around since forever, but we didn't had time to debug it properly...

**Comment by L4BORG** [comment] 2018-09-06 15:44
Also why would plugin messaging fail? There are no errors just missing votes. It doesn't matter if players are online or not (so votes would be sent with delay) in both cases votes simply won't come through (randomly).

**Comment by AmazedMender16** [comment] 2018-09-06 15:46
Sometimes stops conpletely and requires a restart

**Comment by Ichbinjoe** [comment] 2018-09-06 15:55
Your guess is as good as mine. You can audit the code and see that each vote's forwarding logic is handled independently.

**Comment by Ichbinjoe** [comment] 2018-09-06 15:57
https://github.com/parallelblock/NuVotifier/blob/master/common/src/main/java/com/vexsoftware/votifier/support/forwarding/AbstractPluginMessagingForwardingSource.java#L38

Code in question.

**Comment by Ichbinjoe** [comment] 2018-09-06 19:11
So before more code is written, I think its helpful to try to guess where the issue may lie:

As mentioned above, pluginMessaging is fire and forget, meaning that there is no way for Bungee to ensure that the vote has been received by the target server. If we believe that the message is firing but not being received, logically we should add a ACK mechanism for each vote transited over plugin messaging.

I'm not the largest fan of this for the following reasons:
+ Plugin messaging is carried over the Minecraft protocol, which itself is carried over TCP which allows us to assume that data being transited will be delivered more or less in one piece and correct.
+ Bungee's pluginMessaging API reports whether or not it was able to fire off the plugin message. If the message is failing out at this point, then Bungee SHOULD report false, a logging message is generated, and the vote cached and attempted again later on a new player join.
+ Spigot's plugin messaging system SHOULD have the same assurances as descried in the first two points.
+ We unit test the encoder and decoder for basically this behavior. We are transiting a standardized JSON object over the plugin messaging channel. There should be no issues with serialization and deserialization that present themselves over time - a failure should occur non-dependent on time.

With these assumptions, we can say with relative confidence that the additional ACK wouldn't help us much, as 1) the protocol is standardized and 2) the transit provides that the message WILL get there, and is especially true because players who's session is hijacked aren't immediately timed out or kicked, meaning our message HAD to have gone over and been processed.

We also aren't in C land, where we can just butcher memory and mess things up.

I don't like blaming other people's APIs, because usually it isn't the other person's code causing the issue. These APIs are (should be) battle tested by other plugins which rely on it more heavily. But if we make the assumptions above, and given that it is a spotty issue that occurs over time, I am otherwise lost as to where to look.

**Comment by L4BORG** [comment] 2018-09-06 19:32
I agree with ACK part, I don't think it's needed and so far we've never had issues with missing plugin messaging data...

Is it possible that forwardSpecific() would quietly fail?

**Comment by L4BORG** [comment] 2018-09-06 19:35
I guess not according to https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/config/ServerInfo.java#L83

**Comment by Ichbinjoe** [comment] 2018-09-06 19:46
Yeah, looking at the backing implementation of this there isn't a clear instance where it would silently fail - it will only return false if there is no player on the server.

That being said, there MAY be a race condition where the player becomes disconnected from the server while we are sending the vote, but like, come on. I'm fairly confident that's not what is happening here.

**Comment by L4BORG** [comment] 2018-09-06 19:51
I don't think that's the issue, since it would also happen when the player is online at the time of voting.

**Comment by Ichbinjoe** [comment] 2018-09-06 19:59
So to absolutely confirm, just to be 100% confident:

You are seeing a "Got a vX vote record from ... -> ..." log message, yet on the remote server, not seeing Got a forwarded vote -> ...

Something that may be needed for consideration is that the forwarding event is performed async of the vote being received:

```   @Override
    public void onVoteReceived(Channel channel, final Vote vote, VotifierSession.ProtocolVersion protocolVersion) {
        if (debug) {
            if (protocolVersion == VotifierSession.ProtocolVersion.ONE) {
                getLogger().info("Got a protocol v1 vote record from " + channel.remoteAddress() + " -> " + vote);
            } else {
                getLogger().info("Got a protocol v2 vote record from " + channel.remoteAddress() + " -> " + vote);
            }
        }

        getProxy().getScheduler().runAsync(this, () -> getProxy().getPluginManager().callEvent(new VotifierEvent(vote)));

        if (forwardingMethod != null) {
            getProxy().getScheduler().runAsync(this, () -> forwardingMethod.forward(vote));
        }
    }
```

Maybe?! Idk, feels like grasping at straws.

**Comment by L4BORG** [comment] 2018-09-06 20:08
We're logging votes to MySQL server on BungeeCord, within VotifierEvent. So that's working as expected, votes are logged, no issues there.

Then on Spigot instances, we would print debug message when VotifierEvent is fired and we would also use this even to execute commands. That's where the issue would occur, event is simply not fired like 1 out of 10 times.

**Comment by Ichbinjoe** [comment] 2018-09-06 20:12
I would be curious is the proxy forward method gets rid of this problem. If it does (and you don't need the features that come with plugin messaging), we will have narrowed down the exposure of this problem a lot.

**Comment by L4BORG** [comment] 2018-09-06 20:15
I was thinking the same... but we have 28 servers on our network so it's going to take some time before we setup everything, since we can't use both forwarding methods. But yea, aside from that I'm kinda running out of ideas...

**Comment by Ichbinjoe** [comment] 2018-09-06 22:54
I mean I hope this doesn't make me look wildly incompetent - I really am out of ideas on how to debug this, and NuVotifier is designed in such a way as to be basically immutable, and I feel like I've reviewed the mutable cases to no avail.

**Comment by L4BORG** [comment] 2018-09-08 22:29
Didn't had the time to moving all servers to proxy forward but I did some more debugging...

one of servers bugged out again...

so I tried sending data via plugin messaging with our custom plugins - and that worked as expected. So BungeeCord is actually sending data to specific server. Of course some players were online...

So I went ahead and loaded small plugin with Plugman...

```	public void onEnable()
	{
		Bukkit.getMessenger().registerIncomingPluginChannel(this, "NuVotifier", this);
	}

	@Override
	public void onPluginMessageReceived(String s, Player player, byte[] bytes) {
		try {
			String message = new String(bytes, StandardCharsets.UTF_8);
			getLogger().info("msg: "+message);
		} catch (Exception e) {
			getLogger().log(Level.SEVERE, "There was an unknown error when processing a forwarded vote.", e);
		}
	}

	public void onDisable()
	{
		Bukkit.getMessenger().unregisterIncomingPluginChannel(this, "NuVotifier", this);
	}
```

This did not work on the server that just bugged out but it did work on other servers... so it seems like nothing is coming in on that channel.

I went ahead and change cache: memory to cache: file on BungeeCord, after nvreload I started seeing some data in that file, however not a single vote for the server that just bugged out.

So to recap, no data is actually being sent when the bug would occur and NuVotifier on BungeeCord thinks votes are being forwarded successfully. 

In addition to that data would still came to specific server via plugin messaging, however I was unable to test NuVotifier channel as BungeeCord restart would be needed for that (other channels used by our plugins worked just fine).

So I'm not sure if specific channels on BungeeCord are bugging out or NuVotifier is bugging out or Spigot server is causing this. But since we're running BungeeCord for weeks, months even without restart and the issue would come and go as Spigot instances are being restarted I'm guessing the problem lies somewhere there... as AFAIK NuVotifier won't check server status (online/offline) and try to store state, instead it's just sending messages and storing them if they can't be delivered.

**Comment by L4BORG** [comment] 2018-09-08 23:01
Reloading NuVotifier on bugged spigot instance didn't help and it doesn't make sense why some Spigot instances would bug out more often than others.

It seems like first restart didn't fix the issue and second restart did... so I'm really out of ideas...

**Comment by Ichbinjoe** [comment] 2018-09-09 13:43
This is a great analysis. Thanks for putting in the time to try to narrow this down.

I'm wondering whether the plugin messaging mechanic breaks down over time or whether we are triggering the plugin messages correctly...

I'm becoming more convinced this isn't nuvotifier on the bungee at least. The behavior sounds like players are online and thus the message was sent.

**Comment by L4BORG** [comment] 2018-09-09 21:46
So I changed my mind, I don't think we will be switching to proxy forwarding, instead I've decided to code own vote forwarding via plugin messaging. So we will be using NuVotifier, but just on BungeeCord and then we will be sending votes to Spigot instances in VotifierEvent (on BungeeCord) - but on custom plugin messaging channel, not the one used by NuVotifier. I've also implemented own cache for servers with zero players.

Here I'd like to mention a couple of things, possible issues in NuVotifier, but not necessary the cause for missing votes...

- votes in memory have no TTL? isn't that memory leak by definition? I don't think this could causing missing votes tho...

- there is no throttle when missing (cached) votes are sent? How many votes could NuVotifier send once the first player hits the server? After a few hours? Days? I think this is causing "Too many packets" false kick in some cases, even server crash if 1000s votes are sent at once.

I didn't dig around NuVotifier code too much, so I'm assuming that's how it works...

Instead of current cache I'd recommend using Guava and implementing some kind of throttle.

Anyhow, we will start testing new "system" in a few hours and I guess within a few days (or sooner) we should know if BungeeCord/Spigot is the reason for this (would mean plugin messaging is somehow broken) or NuVotifier.

**Comment by Ichbinjoe** [comment] 2018-09-10 17:20
So to address your points:

The memory cache was never actually meant to be used in production (I know this is documented SOMEWHERE), however this is absolutely a missed change when vote TTLs were added to the file backing. That being said, I'm not sure if this is the best advice going forward, as I know some people (including the servers I work for) have configurations where a file cache is completely pointless as the file is wiped away on new start. Probably well time for this to become more accepted.

You are completely right about the missing throttle. This was overlooked - I wouldn't be surprised if this is where some votes got lost.

**Comment by Ichbinjoe** [comment] 2018-09-10 17:21
I have stuff, and those changes + a fix for #101 will be in a new release because these are pressing issues

**Comment by L4BORG** [comment] 2018-09-11 06:08
We had the same issue when using "cache: file", on two different networks actually, so I don't think cache: memory is the reason for missing votes. Anyhow I'm happy to report everything is working well so far.

**Comment by L4BORG** [comment] 2018-09-11 17:36
I take that back, the issue would still occur every now and then, but not as often as with votifier. We were trying to send 50 votes or less at once, I guess that's still too much.

**Comment by Ichbinjoe** [comment] 2018-09-11 19:48
I plan on implementing a throttle sometime in the next 2 days... I am currently working on adding a memory scrubbling task to the memory cache while doing quite a bit of refactoring of some of the structures used.

**Comment by Ichbinjoe** [comment] 2018-09-12 02:16
So both pluginMessage throttling as well as memory cache ttls have been implemented. Please validate this behavior.

As for the root cause, we will see if these measures help at all.

**Comment by Ichbinjoe** [comment] 2018-09-13 17:27
Also gotta love how md_5 completely misses the real point....

Channel name is irrelevant to the problems you are seeing. If the messages are being bounced due to a bad channel name, BungeeCord _should_ be throwing that as an exception.

**Comment by andrewkm** [comment] 2018-10-13 14:50
@Ichbinjoe my players have too noticed that votes now stop forwarding.
This just started happening recently around the time of this issue.
https://www.ecocitycraft.com/forum/threads/voting-not-working-on-sb.178000/

Would love this to be looked at if you get a chance. At this time, we have made absolutely no changes to our nuvotifier setup, yet votes simply stopped going through. They are logged properly in bungee's cached-votes.json - however they are not being forwarded to the servers. :(

**Comment by L4BORG** [comment] 2018-10-13 16:03
@Ichbinjoe @andrewkm

I'm not sure but I think Bungee must be bugging out if plugin is spamming via plugin messaging. We've kinda fixed the issue by custom solution...

We use NuVotifier on Bungee only, with own Guava cache, so all votes are processed on Bungee and stored (and expired) there.

Then we would forward votes to specific servers (if and when 1+ players are online) via our own custom plugin messaging, it's nothing special really, the only difference is that we're sending votes in bulk, so like every few seconds JSON string with 50 votes is being sent, instead of spamming tons of short messages (with each having only one vote). Should be fairly easy to implement with NuVotifier since it's already using JSON, but I'm not too familiar with codebase (and its support for sponge etc.) so I went for own solution.

It seems like this fixed the issue for us on all servers on two different networks (35+ spigot instances) without exception for past month or so.

Might we worth to ask md_5 to look into it, but apparently he's not willing to listen to me so... yea... We're already running custom build of Bungee anyways and I'm not willing to kill more time on this and argue back and forth with him.

**Comment by Ichbinjoe** [comment] 2018-10-13 16:12
Yeah, md_5 has been very uncooperative, and especially from the evidence put forward above, there is obviously some external causing this issue....

Regardless, if @L4BORG is seeing success in packaging up the votes and sending them as one message, there can probably be a mode to send them in bulk. I can't afford to do free work right now, so if someone wants to PR this I would be more than happy to review & accept it. If that doesn't happen, I can probably fit this in to my schedule in a week or two. Sorry for the inconvenience, but life does take the priority in this stuff.

**Comment by andrewkm** [comment] 2018-10-16 16:11
No worries. Thank you so much @Ichbinjoe - if you get a fix going that would be great. Whenever you're free :)

**Comment by andrewkm** [comment] 2018-10-28 17:51
Any updates or recommendations on this @Ichbinjoe 
Nothing I’ve tried seems to work for us.

**Comment by Ichbinjoe** [comment] 2018-12-10 17:59
Experimental support was pushed to master. Please update and let me know if it works at all.

**Closed by Ichbinjoe** 2018-12-10 17:59 UTC
