### ISSUE TITLE
Saved vote issue

### ISSUE THREAD

**Issue by Kirrasio** [parallelblock/NuVotifier#59] opened 2018-01-23 22:09 UTC
After a day of having nuvotifier up and cashe-votes.json saving, it then makes throws this error and it seems to be haulting the nuvotifier plugin completely.

https://pastebin.com/iWMZFndL

If I attempt to restart the bungee without deleting the cashe-votes.json nuvotifier just doesn't start up at all. 

Spigot version 9b8bba4-bdcc7c7
NuVotifier 2.3.6

**Comment by Ichbinjoe** [comment] 2018-01-24 04:43
This is definately an issue I want to fix right away.

Could you upload your cached-votes.json file? Is there anything inside of it?

The quick fix would be to delete the cache (which will be the eventual fix, because the data probably can't be saved) but I still want to figure out why it made this decision anyways.

**Comment by Ichbinjoe** [comment] 2018-01-24 04:50
Yeah so I looked over, and NuVotifier is using a json dependency that is > 4 years old now 😞.

I will update the version. I plan on adding a CI in the next few days, so hang tight and you should be able to get a dev version.

**Comment by Kirrasio** [comment] 2018-01-24 05:53
Thank you for getting back to me so fast!
I know you already found the source but here's the json. Do you have a paypal link for donations? (I've used your plugin for a few years now and has always been one of those life saver plugins for a server like ours.)
https://pastebin.com/2h0j30hk

**Comment by Ichbinjoe** [comment] 2018-01-25 01:08
I should have a CI up and serving builds you can test in a few days. I'll comment back when that is.

**Comment by recon88** [comment] 2018-03-01 11:21
Just encountered the same issue. Any progress on the CI?
If the fix was already pushed, I can just compile it myself.

**Comment by Ichbinjoe** [comment] 2018-03-03 01:31
recon88 thanks for the feedback. I'll have to work on this more. I plan on doing this some tonight.

**Comment by Ichbinjoe** [comment] 2018-03-29 01:49
Does this issue still exist with the latest version: https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

**Comment by Ichbinjoe** [comment] 2018-03-30 04:49
https://github.com/stleary/JSON-java/issues/372

This issue appears to stem from our serialization library. I am not confident the issue is the same (especially because I could not find a sample stack trace) but from looking at the fix it may cover this issue.

**Comment by recon88** [comment] 2018-03-30 10:15
Downloaded the version from above. Still the same error and output in the file.

**Comment by Ichbinjoe** [comment] 2018-03-30 15:46
I am going to switch to a different JSON library then. I’m convinced this is a library issue and not a nuvotifier code issue. Should be able to do this in the next few days

**Comment by recon88** [comment] 2018-03-30 15:50
Can't you just use the YAML Configuration API of Bungee and Bukkit to save the queue instead of relying on external Libraries?

**Comment by Ichbinjoe** [comment] 2018-03-30 22:25
Not without breaking backwars compatability, no. We would still have to read off the old cached-votes.json file.

NuVotifier currently runs off of the org.json json library, which touts itself as the 'reference' JSON library, however its obvious that just because its the reference doesn't mean its been well vetted. Removing JSON from the equation entirely also isn't an option because the Votifier v2 spec requires JSON which brings in another reverse compatibility issue. So to be short, I don't think removing JSON is the right solution. However, moving to a more battle tested library is logical.

I will be looking to move to GSON or Jackson-Core. Because we don't depend on data-bound mechanics of these libraries, it shouldn't really matter to which one of each we use. In the end, I'll probably choose GSON because it is smaller than Jackson-Core, and I know others are much more familiar with it.

**Comment by L4BORG** [comment] 2018-03-31 09:15
150kb larger .jar is not really an issue tho?

**Comment by Ichbinjoe** [comment] 2018-03-31 21:56
Latest is now using GSON. Try testing off of it instead.

**Comment by L4BORG** [comment] 2018-04-02 09:29
```11:26:35 [WARNING] Exception encountered when loading plugin: NuVotifier
java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set;
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.load(FileVoteCache.java:73)
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:32)
    at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:261)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)```

**Comment by recon88** [comment] 2018-04-02 10:01
Can confirm. Same error as above when you start the server.

**Comment by Ichbinjoe** [comment] 2018-04-03 05:49
I neglected to relocate gson within com.vexsoftware.*, so I think a plugin both of you use also uses gson, but collided with my version of gson. I didn't catch this, as I test on clean servers.

Try with the latest build, it has relocated dependencies.

**Comment by Ichbinjoe** [comment] 2018-04-04 03:57
If someone can confirm that the above dev build works, I'm going to cut a new 2.3.7 version, as this is serious enough.

**Comment by recon88** [comment] 2018-04-04 09:47
Aren't you testing it before uploading? It's still missing classes.  
```
11:45:02 [WARNING] Exception encountered when loading plugin: NuVotifier
java.lang.NoClassDefFoundError: com/vexsoftware/votifier/google/common/io/Files
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.load(FileVoteCache.java:49)
    at com.vexsoftware.votifier.bungee.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:32)
    at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:261)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: com.vexsoftware.votifier.google.common.io.Files
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more
```

**Comment by Ichbinjoe** [comment] 2018-04-04 14:39
Recon, I perform a basic “smoke” test before committing, but usually do not perform an indepth functional test. In-depth functional tests require time, and this project is not something I receive anything back from. All of my work on this project is volunteer work.

Obviously I cannot get this right to save my life, so I will be sure to test this functionality more thoroughly.

**Comment by recon88** [comment] 2018-04-04 14:44
I do understand, but it only requires a simple bungeecord start to see if the plugin at least loads which wasn't the case for the last two builds. I'm more than happy to help and do more in-depth testing after the plugin loads without issues :)

**Comment by Ichbinjoe** [comment] 2018-04-05 01:35
https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

All CI builids are sent to here.

**Comment by recon88** [comment] 2018-04-05 09:54
I guess the issue lies in your code. Same error and same file content as before.

```
java.lang.StackOverflowError
	at java.io.BufferedWriter.write(BufferedWriter.java:226)
	at java.io.Writer.write(Writer.java:157)
	at com.vexsoftware.votifier.google.gson.stream.JsonWriter.string(JsonWriter.java:566)
	at com.vexsoftware.votifier.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
	at com.vexsoftware.votifier.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:307)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:756)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
	at com.vexsoftware.votifier.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:759)
```

```
{"version":2,"players":{},"servers":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{"lobby":{
´´´

**Comment by Ichbinjoe** [comment] 2018-04-05 14:40
@recon88 can you zip up your entire nuvotifier directory so I can test this out locally with your cache / configuration. I think I spotted the issue but would like a dirty cache to test with / safely recover from. You can take out all of the rsa and tokens, I only want the base config and the bad cache.

**Comment by recon88** [comment] 2018-04-05 16:52
I'm testing locally with a fresh bungee instance all the time. If you want to trigger the exception, just set cache to file and cast a testing vote with a site like that: https://mctools.org/votifier-tester

**Comment by Ichbinjoe** [comment] 2018-04-06 05:53
Yeah totally figured it out. Latest on CI.

**Comment by recon88** [comment] 2018-04-06 10:12
Saving and loading seems to be working now but I actually found another issue.

What I did:
- Cast multiple votes with different names
- Stop Bungee and check the cache file (should be fine)
- Start Bungee and connect with an account that voted earlier and is in the cache
- That person should receive their rewards properly
- Stop Bungee again and check the cache file again

Result:
```
{"version":2,"players":{},"servers":{}}
```
All cached votes are gone instead of just the one from the person that has joined.

**Comment by Ichbinjoe** [comment] 2018-04-06 23:56
@recon88 so this version appears to work as expected?

**Comment by recon88** [comment] 2018-04-07 10:05
Didn't have any issues so far when trying.

**Comment by L4BORG** [comment] 2018-04-07 10:10
So json is not valid?

**Closed** 2018-04-07 15:49 UTC
