### ISSUE TITLE
Offline votes forwarding

### ISSUE THREAD

**Issue by AmazedMender16** [parallelblock/NuVotifier#83] opened 2018-05-16 16:59 UTC
[NuVotifier] Successfully evicted 8 votes to player 'AmazedMender16.

Thats what shows up in the console. Its adding a ' infront everyones name and the votes never get passed thru to the server the user is on!

EDIT: Offline votes are also case sensitive.

**Comment by AmazedMender16** [comment] 2018-06-19 08:52
Any update on this issue?

**Comment by Ichbinjoe** [comment] 2018-08-02 16:04
The logging message is not related to a vote-not-forwarding situation. Logging message has been fixed in b494e1d

**Comment by AmazedMender16** [comment] 2018-08-02 16:11
What could cause it not to forward offline votes then?
I would be able to troubleshoot if you could let me know

**Comment by Ichbinjoe** [comment] 2018-08-02 16:12
Please leave detailed reproduction steps - what names you used, services you used, logs, lots of stuff would help.

Offline votes are case sensitive by design. Is there a reason they should not be?

**Comment by Ichbinjoe** [comment] 2018-12-10 17:59
Please try with latest and reopen if its still happening.

**Closed by Ichbinjoe** 2018-12-10 17:59 UTC
